var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Seg",
            "tue": "Ter",
            "wed": "Qua",
            "thu": "Qui",
            "fri": "Sex",
            "sat": "Sab",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Abr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Set",
            "oct": "Out",
            "nov": "Nov",
            "dec": "Dez"
        },
        "no_implemented": "Não Implementado ainda",
        "to_date_view": "Cique para ver a data corrente",
        "i_undefined": "Indefinido",
        "allday_event": "Evento para um dia inteiro",
        "repeat_event": "Repetir Evento",
        "time": "Hora",
        "event": "Eventos",
        "location": "Localização",
        "participant": "Participantes",
        "get_data_exception": "Problemas ao obter os dados",
        "new_event": "Novo Evento",
        "confirm_delete_event": "Você confirma apagar este evento?",
        "confrim_delete_event_or_all": "Você quer repetir todos os eventos ou apenas este evento? \r\nPressione [OK] para apagar apenas este evento, pressione [Cancelar] para cancelar todos os eventos",
        "data_format_error": "Erro no formato da data",
        "invalid_title": "O título do evento não pode ficar em braco e nem conter as tags $<>",
        "view_no_ready": "A página não está pronta",
        "example": "ex., Encontrar com chefe hoje",
        "content": "O Quê?",
        "create_event": "Criar um Evento",
        "update_detail": "Editar Detalhes",
        "click_to_detail": "Ver Detalhes",
        "i_delete": "Apagar",
        "day_plural": "Dias",
        "others": "Outros",
        "item": ""
    }
});
